name: CI

on:
  push:
    paths:
      - 'contract/**'
  pull_request:
    paths:
      - 'contract/**'
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        node: [16]

    name: Foundry project
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install Node dependencies
        run: |
          npm ci
        working-directory: contract

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Show Forge version
        run: |
          forge --version
        working-directory: contract

      - name: Run Forge fmt
        run: |
          forge fmt --check
        id: fmt
        working-directory: contract

      - name: Show remappings
        run: |
          forge remappings
        working-directory: contract

      - name: Run Forge build
        run: |
          forge build --sizes
        id: build
        working-directory: contract

      - name: Run Forge tests
        run: |
          forge test -vvv
        id: test
        working-directory: contract